version: "3"

includes:
  ui:
    taskfile: ui/Taskfile.yml
    dir: ui
    internal: true

  cmd:
    taskfile: cmd/Taskfile.yml
    dir: cmd
    internal: true

tasks:
  install:
    desc: install npm packages
    deps:
      - ui:install
      - cmd:install

  test:
    desc: run tests
    deps:
      - ui:test

  run:
    desc: run the UI
    deps:
      - ui:run

  build:
    desc: Build the UI and CLI
    deps:
      - ui:build
    cmds:
      # Create symlink from ui/dist to cmd/src/commands/web/dist
      # Use '|| true' to ignore error if link already exists
      - ln -sf ../../../../ui/dist ./cmd/src/commands/web/dist || true
      # Update the import statements in index.ts
      - ./cmd/src/commands/web/update-web-imports.sh
      # Now build the cmd
      - task: cmd:build

  artifacts:
    desc: Create release artifacts (zip file)
    deps:
      - build # Ensure build is complete before creating artifacts
    cmds:
      # Create a directory to hold all artifacts
      - mkdir -p analog
      # Copy UI build artifacts
      - cp -r ui/dist ./analog
      # Move CLI executables
      - mv cmd/analog-linux ./analog/
      - mv cmd/analog-windows.exe ./analog/
      - mv cmd/analog-macos ./analog/
      # Zip the combined artifacts
      - zip -r analog.zip analog
      # Cleanup the temporary packaging directory
      - rm -rf analog
