version: "3"

tasks:
  install:
    desc: install npm packages
    cmds:
      - bun i

  build:
    desc: transpile and bundle
    cmds:
      - > 
        bun build 
        ./src/main.ts 
        ./src/commands/summary/worker.ts 
        ./src/commands/merger/worker.ts 
        --outdir ./cli 
        --target bun
