version: "3"

tasks:
  install:
    desc: install npm packages
    cmds:
      - pnpm i

  test:
    desc: run tests
    cmds:
      - pnpm test

  build:
    desc: transpile and bundle
    cmds:
      - pnpm build
      - cp analog.sh analog.ps1 analog
  
  run:
    desc: run
    cmds:
      - pnpm start
