version: "3"

tasks:
  install:
    desc: install npm packages
    cmds:
      - pnpm i

  test:
    desc: run tests
    cmds:
      - pnpm test

  build:
    desc: transpile and bundle
    cmds:
      - rm -rf ./dist || true
      - pnpm build

  run:
    desc: run
    cmds:
      - pnpm start
